use_frameworks!

platform :ios, '9.0'

target 'MBProgressHUD-CXExtension_Example' do
  pod 'MBProgressHUD-CXExtension', :path => '../'

  target 'MBProgressHUD-CXExtension_Tests' do
    inherit! :search_paths

    
  end
end
